### ISSUE TITLE
support reading binary output from bazel-bin/

### ISSUE THREAD

**Issue by ixdy** [kubernetes/release#250]
Currently we assume that release tars are under `$KUBE_ROOT/_output/release-tars`, binaries are under `$KUBE_ROOT/_output/release-stage`, and that we can locally stage things to `$KUBE_ROOT/_output/gcs-stage`.

With Bazel builds, the release tars are under `$KUBE_ROOT/bazel-bin/build/release-tars`, the binaries are under `$KUBE_ROOT/bazel-bin/...` (not one central location), and it's not clear where `gcs-stage` should go.

I'm not sure whether we should try to emulate the non-bazel directory structure for bazel-build binaries (copy/symlink everything into `_output/bazel` or equivalent), update `lib/releaselib.sh` to support bazel paths, or something else entirely.

It's also not clear how bazel crossbuilds might work, and where their output would end up.

**Comment by ixdy** [comment]
cc @spxtr @mikedanese

**Comment by mikedanese** [comment]
done?

**Comment by ixdy** [comment]
nope, not yet. `push-build.sh` still won't handle bazel-built artifacts correctly.

**Comment by ixdy** [comment]
This is fixed.
