### ISSUE TITLE
Container images are signed with the wrong identity

### ISSUE THREAD

**Issue by puerco** [kubernetes/release#2789]
### What happened:

Sometime around the end of October,  something broke signature replication in `kpromo` and existing signatures on staged images are no longer propagated to the production registry. Shortly after that, all container images started to get signed with the service account running the image promoter pod instead of our signer account.  

[Full discussion on slack here](https://kubernetes.slack.com/archives/CJH2GBF7Y/p1669761613115499)

We can see the evolution of the problem by looking at the last patch releases:

```
cosign verify k8s.gcr.io/kube-apiserver:v1.24.6   | jq '.[].optional.Subject'
...
"krel-staging@k8s-releng-prod.iam.gserviceaccount.com"
"krel-trust@k8s-releng-prod.iam.gserviceaccount.com"


cosign verify k8s.gcr.io/kube-apiserver:v1.24.7   | jq '.[].optional.Subject'
...
"krel-trust@k8s-releng-prod.iam.gserviceaccount.com"


cosign verify k8s.gcr.io/kube-apiserver:v1.24.8   | jq '.[].optional.Subject'
...
"k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com"
```

### Problem fix and remediation

Fix and remediation is now required to correct the problem to stop corrupting more signatures and then we need remediation to ensure our images are consistently signed. In short, we need to:

#### Fix the problem:

* Correct signature replication
* ~Fix the bug causing signatures to be done with the right identity~
done: ~ https://github.com/kubernetes-sigs/promo-tools/pull/681

#### Remediate the bad signatures

* Copy any signatures from staging
* Resign images with the correct identity

Thanks to @mattmoor for reporting the problem.

**Comment by puerco** [comment]
We are now considering dropping the staging signatures in favor of just having signed provenance. We are considering reworking those signatures anyway as part of https://github.com/kubernetes/release/issues/2618  .

On one hand, those signatures have been done from inside the release process so they have been always insecure. But on the other, we need to keep the replication code because we want to carry not only signatures but also any sboms and attestations.

**Comment by saschagrunert** [comment]
Is this issue now resolved with https://github.com/kubernetes/test-infra/pull/28180?

**Comment by xmudrii** [comment]
@saschagrunert No, in fact, they don't have too much in common, but I linked it so we have recent promo fixes in a single place.

Signature replication is still not working as expected. We're still to decide if we want to continue replicating or drop it in favor of signed provenance, although, we might have to fix replication anyways because of SBOMs. We also need to figure out how to fix images that are already promoted with wrong and missing signatures.

@puerco and I did some investigation about this and we might have some idea about this, but we need to investigate it a bit more.

**Comment by xmudrii** [comment]
Let me try to break down what issues we found and explain where are with our investigation.

## [FIXED] Wrong identity

At some point, we started signing images with the wrong identity: `k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com` instead of `krel-trust@k8s-releng-prod.iam.gserviceaccount.com`:

```
cosign verify k8s.gcr.io/kube-apiserver:v1.24.8   | jq '.[].optional.Subject'
...
"k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com"
```

This is fixed with https://github.com/kubernetes-sigs/promo-tools/pull/681.

## [Observing] Images being double-signed

Occasionally, images are double-signed with the same identity, so we end up in a situation such as this one:

```
$ cosign verify k8s.gcr.io/kube-apiserver-arm64:v1.24.6 | jq '.[].optional.Subject'

Verification for k8s.gcr.io/kube-apiserver-arm64:v1.24.6 --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline
  - Any certificates were verified against the Fulcio roots.
"krel-staging@k8s-releng-prod.iam.gserviceaccount.com"
"krel-trust@k8s-releng-prod.iam.gserviceaccount.com"
"krel-trust@k8s-releng-prod.iam.gserviceaccount.com"
```

Note that we have the staging signature (as expected), and two `krel-trust` signatures (**only one is expected**).

I think that this happens because we run the promotion process two times in parallel. The first time in a postsubmit that's triggered after merging the PR, and the second time in a periodic that's automatically triggered each hour. The promotion process takes a lot of time for Kubernetes release -- at least one hour, so there's a very high chance those two jobs are going to conflict.

Additionally, if we take a look at the logs for the promotion process for v1.24.6, I think that we can confirm that signing happened two times for some images:

* Postsubmit: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-k8sio-image-promo/1572614837010173952
* Periodic, that got triggered 4 minutes after the postsubmit _started_: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-k8sio-image-promo/1572616813148114944

The issue with running the promotion process twice in parallel should be fixed with https://github.com/kubernetes/test-infra/pull/28180. However, after discussing it with @puerco, we're not 100% sure that double-signing with the same identity is possible, so we're still observing if this is related to triggering the promotion process two times or due to some potential bug in promo-tools. From some additional investigation, I think double signing with the same identity is possible, so we'll keep observing this issue, hoping that what we did will fix this issue.

## [Under Investigation] Replication of staging signatures doesn't work

We started observing that the staging signatures are not replicated properly, so we end up in a situation such as this one:

```
$ cosign verify k8s.gcr.io/kube-apiserver:v1.24.8 | jq '.[].optional.Subject'

Verification for k8s.gcr.io/kube-apiserver:v1.24.8 --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline
  - Any certificates were verified against the Fulcio roots.
"k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com"
```

Note that there's only one signature, but we expect two signatures (`krel-staging` signature is missing).

My first thought about this issue is that we're seeing this because:

- The CopySignatures function takes a list of SignedEdges: https://github.com/kubernetes-sigs/promo-tools/blob/adf241e4c2263e28f4856af6e9b7585b6346fc5d/promoter/image/promoter.go
- SignedEdges in this case is a slice of staging images. For each SignedEdge:
  - Source is a staging image: `gcr.io/k8s-staging-kubernetes/...`
  - Destination is random: we choose one possible destination where we'll copy the staging signature to
  - Note: there are 30 staging images per release, so we have 30 SignedEdges per release. If we promote both official (e.g. v1.24.6) and next rc (e.g. v1.24.7-rc.0), we have 60 SignedEdges in total
- In CopySignautres: we take each SignedEdge/staging image (`for` loop) -- and copy from the source (`gcr.io/k8s-staging-kubernetes`) to a destination. Copy in this context means copying the signature

I initially thought that we can fix this by extending this so that we copy to all destinations instead of to only one destination. This is wrong and @puerco pointed me out that we do that later. We run CopySignatures, then we sign using the production identity, and then we replicate both staging and production signatures from one destination to all other possible destinations.

A possible root cause of this issue is that there's **NO** guarantee that:

- We're going to sign (with the production identity) the same edge to which we copied the staging signatures
- We're going to replicate from the same edge that we copied the staging signature to

If that's true, we need to modify the [SignImages function](https://github.com/kubernetes-sigs/promo-tools/blob/adf241e4c2263e28f4856af6e9b7585b6346fc5d/promoter/image/promoter.go#L172), to take into the account where we copied the staging signature to, and to sign exactly that edge. After that, the final replication process should use that edge as its source for copying to other edges.

However, we stopped our investigation here. We are thinking if we should do this at all or instead move to just signing the provenance. We still need to discuss how are we going to proceed here.

## [Not started] Remediate the bad signatures

There are many images affected by those issues described above. We need to think about how can we fix this for those images. Those images are already promoted, making this a little bit more complicated. I thought about this, but I don't really know how we can do this and this is something that we should discuss with @puerco.

**Comment by saschagrunert** [comment]
Thank you for this great summary @xmudrii! 

> We are thinking if we should do this at all or instead move to just signing the provenance.

What would that mean technically? Just singing the provenance file and not the images at all?

**Comment by xmudrii** [comment]
We still need to remediate the bad signatures
/remove-lifecycle stale

**Comment by xmudrii** [comment]
We still have to fix some issues outlined in https://github.com/kubernetes/release/issues/2789#issuecomment-1339221532
/remove-lifecycle stale

**Comment by saschagrunert** [comment]
Closing as the signing infrastructure has changed significantly since this was filed.
